name: Fetch BW data every minute

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch URL
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          curl -s "https://wahlen.bw-btw25.23degrees.eu/assets/kreise.csv" -o "data/btw25-bw-kreise_$TIMESTAMP.txt"
          curl -s "https://wahlen.bw-btw25.23degrees.eu/assets/gemeinden.csv" -o "data/btw25-bw-gemeinden_$TIMESTAMP.txt"

      - name: Commit and Push
        run: |
          git config --global user.name "volzinnovation"
          git config --global user.email "39283695+volzinnovation@users.noreply.github.com"
          git add data/
          git commit -m "Fetched data at $(date +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
          git push
